net/frr7: fix build due to -Werror clash during configure
Likely caused by llvm update to version 13.

    configure:9654: checking for the pthreads library -lpthread
    configure:9692: cc -std=gnu11 -o conftest -O2 -pipe  -std=gnu99 -fstack-protector-strong -fno-strict-aliasing  -fno-omit-frame-pointer -funwind-tables -Wall -Wextra -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith -     Wbad-function-cast -Wwrite-strings -Wundef -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers  -Werror -I/usr/local/include -I/usr/local/include  -L/usr/local/lib -L/usr/local/lib -Wl,-rpath,/usr/local/li     b -fstack-protector-strong  conftest.c -lpthread  >&5
    conftest.c:27:51: error: parameter 'a' set but not used [-Werror,-Wunused-but-set-parameter]
                            static void routine(void *a) { a = 0; }
    1 error generated.