security/strongswan: fix plist
In the old days committers would have been educated enough to know
that tools exist for these types of things or that someone else would
have double checked, but not any longer ;)

  >>> Package list inconsistency for security/strongswan (strongswan)
  [20251110034217] ====> Checking for pkg-plist issues (check-plist)
  ===> Parsing plist
  ===> Checking for items in STAGEDIR missing from pkg-plist
  Error: Orphaned: %%ETCDIR%%.d/iptfs.conf.sample
  Error: Orphaned: %%DATADIR%%/templates/config/strongswan.d/iptfs.conf
  ===> Checking for items in pkg-plist which are not in STAGEDIR
  ===> Error: Plist issues found.