Revert "textproc/py-sphinx: sync with upstream"
This reverts commit 3a51a2bfbbed33a696ea899fd370c235bc7a5702.

>>> Aborted version 4.6.0 for dns/powerdns-recursor
>>> Aborted version 7.4_6 for net/frr7

To be more precise:

Exception occurred:
  File "/usr/obj/usr/ports/net/frr7/work/frr-frr-7.4/doc/user/conf.py", line 369, in setup
    app.add_javascript('overrides.js')
AttributeError: 'Sphinx' object has no attribute 'add_javascript'