Revert "security/nss: sync with upstream"
This reverts commit 6ec78d6ddf472258b55b8fa9f91139bee1fc17e1.
Nightly build error:

The prerequisites of 'export' are being made.
Live child 0x8006bb6c0 (nss) PID 40435
../../coreconf/rules.mk:202: *** multiple target patterns.  Stop.
Reaping losing child 0x8006bb6c0 PID 40435
gmake[4]: *** [../coreconf/rules.mk:44: nss] Error 2
Removing child 0x8006bb6c0 PID 40435 from chain.
Reaping losing child 0x8006c02a0 PID 39128
gmake[3]: *** [coreconf/rules.mk:44: lib] Error 2
Removing child 0x8006c02a0 PID 39128 from chain.
Reaping losing child 0x8006dc2a0 PID 39043
gmake[2]: *** [manifest.mn:26: prepare_build] Error 2
Removing child 0x8006dc2a0 PID 39043 from chain.
[20210808110432] ===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/security/nss
*** Error code 1

Stop.
make: stopped in /usr/ports/security/suricata