Revert "devel/gdb: sync with upstream"
This reverts commit 19283cfe4ae456d13bf0bf91f7c9a4c918279508.

/usr/bin/ld: ../libctf/.libs/libctf.a(ctf-archive.o): relocation R_X86_64_TPOFF32 against `a local symbol' can not be used when making a shared object; recompile with -fPIC
../libctf/.libs/libctf.a: could not read symbols: Bad value
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[3]: *** [Makefile:1928: kgdb] Error 1
gmake[3]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../libctf/.libs/libctf.a(ctf-archive.o): relocation R_X86_64_TPOFF32 against `a local symbol' can not be used when making a shared object; recompile with -fPIC
../libctf/.libs/libctf.a: could not read symbols: Bad value
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[3]: *** [Makefile:1919: gdb] Error 1
gmake[2]: *** [Makefile:8273: all-gdb] Error 2
gmake[1]: *** [Makefile:851: all] Error 2
[20200615005949] ===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1