Revert "net-mgmt/netdata: sync with upstream"
This reverts commit 7fd788c96d4e11d118929b038f191e52ac3a7005.

libnetdata/socket/security.c:71:16: error: use of undeclared identifier 'TLS1_3_VERSION'
        return TLS1_3_VERSION;
               ^
libnetdata/socket/security.c:74:12: error: use of undeclared identifier 'TLS_MAX_VERSION'
    return TLS_MAX_VERSION;
           ^
2 errors generated.
--- libnetdata/socket/security.o ---
*** [libnetdata/socket/security.o] Error code 1