Revert "net/ntopng: sync with upstream"
This reverts commit f620ef4161383fc9cf29fa66c41121d9d47afcf1.

>>> Stage ports-LibreSSL was aborted due to an error, last 400 lines as follows:
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from ldump.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lfunc.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lgc.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from llex.c:16:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lmem.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lobject.c:20:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lopcodes.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lopcodes.h:10:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/llimits.h:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lparser.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lstate.c:16:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lstring.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from ltable.c:29:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from ltm.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lundump.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
lundump.c:237:33: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
  checkliteral(S, LUA_SIGNATURE + 1, "not a");  /* 1st char already checked */
                  ~~~~~~~~~~~~~~^~~
lundump.c:237:33: note: use array indexing to silence this warning
  checkliteral(S, LUA_SIGNATURE + 1, "not a");  /* 1st char already checked */
                                ^
                  &             [  ]
2 warnings generated.
In file included from lvm.c:19:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lzio.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lauxlib.c:25:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lbaselib.c:18:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lbitlib.c:13:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lcorolib.c:15:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from ldblib.c:17:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from liolib.c:20:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lmathlib.c:16:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from loslib.c:19:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lstrlib.c:22:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from ltablib.c:17:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lutf8lib.c:18:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from loadlib.c:21:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from linit.c:32:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from lua.c:17:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from luac.c:18:
In file included from /usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/lua.h:16:
/usr/obj/usr/ports/net/ntopng/work/ntopng-5e649a2/third-party/lua-5.3.5/src/luaconf.h:64:9: warning: 'LUA_USE_READLINE' macro redefined [-Wmacro-redefined]
        ^
<command line>:3:9: note: previous definition is here
        ^
1 warning generated.
In file included from src/LuaEngine.cpp:182:
src/LuaEngineInterface.cpp.inc:4441:21: warning: unused variable 'ntop_interface' [-Wunused-variable]
  NetworkInterface *ntop_interface = getCurrentInterface(vm);
                    ^
src/LuaEngineInterface.cpp.inc:4489:21: warning: unused variable 'ntop_interface' [-Wunused-variable]
  NetworkInterface *ntop_interface = getCurrentInterface(vm);
                    ^
In file included from src/LuaEngine.cpp:183:
src/LuaEngineNtop.cpp.inc:2627:8: warning: unused variable 'buf' [-Wunused-variable]
  char buf[128];
       ^
3 warnings generated.
ld: error: undefined symbol: gpg_strerror
>>> referenced by visibility.c
>>>               libgcrypt_la-visibility.o:(gcry_strerror) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpg_strsource
>>> referenced by visibility.c
>>>               libgcrypt_la-visibility.o:(gcry_strsource) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpg_err_code_from_errno
>>> referenced by visibility.c
>>>               libgcrypt_la-visibility.o:(gcry_err_code_from_errno) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpg_err_code_from_errno
>>> referenced by visibility.c
>>>               libgcrypt_la-visibility.o:(gcry_err_code_to_errno) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpg_err_code_from_errno
>>> referenced by visibility.c
>>>               libgcrypt_la-visibility.o:(gcry_err_make_from_errno) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpg_err_code_from_errno
>>> referenced by visibility.c
>>>               libgcrypt_la-visibility.o:(gcry_error_from_errno) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpg_strerror
>>> referenced by misc.c
>>>               libgcrypt_la-misc.o:(_gcry_fatal_error) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpg_err_set_errno
>>> referenced by misc.c
>>>               libgcrypt_la-misc.o:(_gcry_strtokenize) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpg_err_set_errno
>>> referenced by misc.c
>>>               libgcrypt_la-misc.o:(_gcry_divide_by_zero) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpg_err_code_from_errno
>>> referenced by misc.c
>>>               libgcrypt_la-misc.o:(_gcry_divide_by_zero) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpgrt_get_syscall_clamp
>>> referenced by global.c
>>>               libgcrypt_la-global.o:(global_init) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpgrt_fopenmem
>>> referenced by global.c
>>>               libgcrypt_la-global.o:(_gcry_get_config) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpgrt_fprintf
>>> referenced by global.c
>>>               libgcrypt_la-global.o:(_gcry_get_config) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpgrt_fprintf
>>> referenced by global.c
>>>               libgcrypt_la-global.o:(_gcry_get_config) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpgrt_fprintf
>>> referenced by global.c
>>>               libgcrypt_la-global.o:(_gcry_get_config) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpgrt_fprintf
>>> referenced by global.c
>>>               libgcrypt_la-global.o:(_gcry_get_config) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpgrt_fprintf
>>> referenced by global.c
>>>               libgcrypt_la-global.o:(_gcry_get_config) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpgrt_fprintf
>>> referenced by global.c
>>>               libgcrypt_la-global.o:(_gcry_get_config) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpgrt_fprintf
>>> referenced by global.c
>>>               libgcrypt_la-global.o:(_gcry_get_config) in archive /usr/local/lib/libgcrypt.a

ld: error: undefined symbol: gpgrt_fprintf
>>> referenced by global.c
>>>               libgcrypt_la-global.o:(_gcry_get_config) in archive /usr/local/lib/libgcrypt.a

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [Makefile:151: ntopng] Error 1
[20201116115838] ===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make: stopped in /usr/ports/net/ntopng
Creating repository in /usr/obj/usr/tools/config/20.7/LibreSSL:amd64/.pkg-new/: .......... done
Packing files for repository: .... done
>>> Running build step: clean
>>> Removing packages set
>>> Creating package mirror set for 20.7.4_176-LibreSSL-amd64... done
-rw-r--r--  1 root  wheel   489M Nov 16 12:58 packages-20.7.4_176-LibreSSL-amd64.tar
>>> ERROR: The build encountered fatal issues!
>>> Aborted version 4.2.d20201102,1 for net/ntopng
*** Error code 1

Stop.
make[1]: stopped in /usr/tools
     1243.41 real       500.67 user       102.77 sys